# Generated by Django 3.0.8 on 2020-08-17 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment_users',
        ),
        migrations.RemoveField(
            model_name='papers',
            name='like_users',
        ),
        migrations.RemoveField(
            model_name='papers',
            name='save_users',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Papers',
        ),
    ]
