# Generated by Django 3.0.8 on 2020-09-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ip',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
