# Generated by Django 3.0.8 on 2020-07-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_ieeeusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='iros2020registered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iros2020_name', models.CharField(max_length=100)),
                ('iros2020_email', models.CharField(max_length=100)),
            ],
        ),
    ]
