# Generated by Django 3.0.8 on 2020-10-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_profile_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('active_user_count', models.PositiveIntegerField(default=0)),
                ('active_time_in_seconds', models.PositiveIntegerField(default=0)),
                ('average_active_time', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OverallActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='overall', max_length=10)),
                ('active_time_in_seconds', models.PositiveIntegerField(default=0)),
                ('average_active_time', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
