# Generated by Django 3.0.8 on 2020-07-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_iros2020registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='paper_id',
        ),
        migrations.AddField(
            model_name='like',
            name='paperid',
            field=models.CharField(default=0, max_length=1553),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='paperlikenumb',
            field=models.CharField(default=0, max_length=1553),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='name',
            field=models.CharField(max_length=1553),
        ),
    ]
