# Generated by Django 3.0.8 on 2020-12-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20201024_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtimeUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.CharField(max_length=50)),
                ('current_location', models.CharField(max_length=50)),
            ],
        ),
    ]
