# Generated by Django 3.0.8 on 2020-07-28 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200728_1113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ieeeusers',
        ),
        migrations.DeleteModel(
            name='iros2020registered',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
