# Generated by Django 3.0.8 on 2020-12-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_realtimeusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimeusers',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
