# Generated by Django 3.0.8 on 2020-08-04 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_papers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Papers',
        ),
    ]
