# Generated by Django 3.0.8 on 2020-08-04 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_delete_papers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.PositiveIntegerField(default=0, null=True)),
                ('like_users', models.ManyToManyField(blank=True, related_name='like_papers', to='polls.Users')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Users')),
            ],
        ),
    ]
