# Generated by Django 3.0.8 on 2020-07-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0005_auto_20200728_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='ieeeusers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ieeeusers_id', models.CharField(max_length=100)),
                ('ieeeusers_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='iros2020registered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iros2020_name', models.CharField(max_length=100)),
                ('iros2020_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1553)),
                ('paperid', models.CharField(max_length=1553)),
                ('paperlikenumb', models.CharField(max_length=1553)),
            ],
        ),
    ]
