# Generated by Django 3.0.8 on 2020-12-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_currenttest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentTest',
        ),
    ]
