# Generated by Django 3.0.8 on 2020-08-04 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_papers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Papers',
        ),
    ]
