# Generated by Django 3.0.8 on 2020-08-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_papers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Papers',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
