# Generated by Django 3.0.8 on 2020-08-04 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_papers_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Papers',
        ),
    ]
