# Generated by Django 3.0.8 on 2020-08-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_delete_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.PositiveIntegerField(default=0, null=True)),
                ('comment', models.TextField(max_length=1500)),
                ('comment_users', models.ManyToManyField(blank=True, related_name='comment_papers', to='polls.Users')),
            ],
        ),
    ]
