# Generated by Django 3.0.8 on 2020-08-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='save_users',
            field=models.ManyToManyField(blank=True, related_name='save_papers', to='polls.Users'),
        ),
    ]
