# Generated by Django 3.0.8 on 2020-08-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_papers_save_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='paper_hitcount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
